name: UI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install modules
        run: npm ci
      - name: execute tests
        run: npm run test:ui
      - name: report artifact
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report/report.html
      - name: junit report
        uses: action-junit-report@v3
        if: always()
        with:
          report_paths: report/report.xml
          fail_on_failure: true
