name: CI

on:
  workflow_dispatch:

jobs:
  API:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install modules
        run: npm ci
      - name: execute tests
        run: npm run test:api
        env:
          RP=true
          RP_TOKEN=${{ secrets.RP_TOKEN }}
          RP_ENDPOINT=${{ secrets.RP_ENDPOINT }}
          RP_PROJECT=${{ secrets.RP_PROJECT }}
      - name: report artifact
        uses: actions/upload-artifact@v3
        with:
          name: API Report
          path: report/report.html
      - name: junit report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: report/report.xml
  UI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install modules
        run: npm ci
      - name: execute tests
        run: npm run test:ui
        env:
          RP=true
          RP_TOKEN=${{ secrets.RP_TOKEN }}
          RP_ENDPOINT=${{ secrets.RP_ENDPOINT }}
          RP_PROJECT=${{ secrets.RP_PROJECT }}
      - name: report artifact
        uses: actions/upload-artifact@v3
        with:
          name: UI Report
          path: report/report.html
      - name: junit report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: report/report.xml
